dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-ci-1
  strategy: git
  api_key:
    secure: LvygDa7PpzbBkEICoMiNDusKRcSqwcJ4IgJEyoP75hCNsOrt6NC3dSRZq8e3ruL1yNtpp4TS2LlbGoG4isvX29muyw5B9kMZG5Z0Hsuqv12I362imjGlN9MrwrKvT9E9Vfzk3/xRn33pYzIK7JtJraAq0AMfXzaPyeuAmtSaBg9FDoERr81k/quCL1WHMyJmiPsirlV6Yozns/H5nDZ3AJN6YqYD7zBeNgzUYOujyi+THI6M3QMyoPfxqglIyDNoC2JFstDne9E+yhhj5ndsPSOd/xUa0JW1nuOjOUV1FCpGuA1GPCtvtAFAmxwzUR2vYweRJDAXpeS9l3+L7Q4cek3zMc6qXWnOE42guUgbEhJSr/0P3rtCcDNEUj0++oB0l5yUxW6HEmV9V07LIyN72BM5/tOUdC5vVEtQPbgwvNfO8tDS3RgW/edq58u/KZC+mPgfRL6OmvbU6Dd7wiok5pgcSBSSJjyXRAydxWv2E/MnfTZ3ghd/d5iCpVcex5aTn95Tne5X+N6PkxtUghlD2dLk0WjP6HV9vWe7c+/nVtielcej60ZfL+1HuppZ3cxodpfnBC/R/nmuiUlzNIGCTJhbOKneLuHAAolPXKAf/LSFj4m05vmue7dkVIavVs42sRyQsn9PJkgyUuHBQFFpp6ML/uqUGoWEsdz5qOgV6ss=
